"""Render the catalog to RESOURCES.md, grouped by type, deadlines flagged."""

from __future__ import annotations

from collections import defaultdict
from datetime import date
from pathlib import Path

from .models import Resource

_TYPE_ORDER = [
    "event", "course", "tutorial", "video", "book",
    "tool", "dataset", "paper", "community", "newsletter", "article", "other",
]
_TYPE_LABEL = {
    "event": "🗓️ Events & live cohorts (time-sensitive)",
    "course": "🎓 Courses",
    "tutorial": "📝 Tutorials & guides",
    "video": "🎬 Videos & lectures",
    "book": "📚 Books",
    "tool": "🛠️ Tools & playgrounds",
    "dataset": "🗂️ Datasets",
    "paper": "📄 Papers",
    "community": "💬 Communities",
    "newsletter": "📰 Newsletters",
    "article": "🧵 Articles",
    "other": "🔗 Other",
}


def render(resources: list[Resource]) -> str:
    active = [r for r in resources if r.status == "active"]
    by_type: dict[str, list[Resource]] = defaultdict(list)
    for r in active:
        by_type[r.type].append(r)

    lines = [
        "# Free AI Resources",
        "",
        f"_Auto-generated by free-yolo on {date.today().isoformat()} · "
        f"{len(active)} active resources._",
        "",
        "> Free resources to **learn, use and understand AI**. "
        "Time-sensitive items (with a start date or deadline) are listed first "
        "so you don't miss them the way we missed Google's 5-Day Gen AI Intensive.",
        "",
    ]

    upcoming = sorted(
        (r for r in active if r.is_time_sensitive),
        key=lambda r: r.event_date or "",
    )
    if upcoming:
        lines += ["## ⏰ Don't miss — has a date/deadline", ""]
        for r in upcoming:
            lines.append(_line(r, show_date=True))
        lines.append("")

    for t in _TYPE_ORDER:
        items = sorted(by_type.get(t, []), key=lambda r: r.title.lower())
        if not items:
            continue
        lines += [f"## {_TYPE_LABEL[t]}", ""]
        for r in items:
            lines.append(_line(r))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _line(r: Resource, show_date: bool = False) -> str:
    bits = [f"- [{r.title}]({r.url})"]
    if r.provider:
        bits.append(f"— _{r.provider}_")
    if show_date and r.event_date:
        bits.append(f"**📅 {r.event_date}**")
    if r.topics:
        bits.append(" ".join(f"`{t}`" for t in r.topics))
    if r.description:
        bits.append("\n  " + r.description.replace("\n", " ").strip())
    return " ".join(bits)


def write(resources: list[Resource], path: Path | str) -> Path:
    path = Path(path)
    path.write_text(render(resources))
    return path
