"""Render the catalog to RESOURCES.md — beginner path first, then grouped by
type (relevance-sorted), with cost and level shown to match the web page."""

from __future__ import annotations

from collections import defaultdict
from datetime import date
from pathlib import Path

from .models import Resource

_TYPE_ORDER = [
    "event", "course", "tutorial", "video", "book",
    "tool", "dataset", "paper", "community", "newsletter", "article", "other",
]
_TYPE_LABEL = {
    "event": "🗓️ Events & live cohorts (time-sensitive)",
    "course": "🎓 Courses",
    "tutorial": "📝 Tutorials & guides",
    "video": "🎬 Videos & lectures",
    "book": "📚 Books",
    "tool": "🛠️ Tools & playgrounds",
    "dataset": "🗂️ Datasets",
    "paper": "📄 Papers",
    "community": "💬 Communities",
    "newsletter": "📰 Newsletters",
    "article": "🧵 Articles",
    "other": "🔗 Other",
}

_COST_LABEL = {"free": "Free", "free-account": "Free · sign-up", "freemium": "Freemium"}
_ADV = {"fine-tuning", "mlops", "evals", "agents", "rag"}

# Curated zero-background itinerary (matched against the live catalog).
_PATH = [
    (["elements of ai"], "No code, no math — understand what AI is and is not."),
    (["3blue1brown"], "See, visually, how a neural network actually works."),
    (["machine learning crash course"], "Your first hands-on ML, right in the browser."),
    (["llm course"], "Cross from AI user to AI builder with language models."),
    (["practical deep learning", "course.fast"], "Build and ship real models, code-first."),
]


def _level(r: Resource) -> str:
    if "fundamentals" in r.topics:
        return "Beginner"
    if any(t in _ADV for t in r.topics):
        return "Intermediate"
    return ""


def _relevance_key(r: Resource):
    # fundamentals first, then fully free, then alphabetical — mirrors the site.
    return (0 if "fundamentals" in r.topics else 1,
            0 if r.cost == "free" else 1,
            r.title.lower())


def render(resources: list[Resource]) -> str:
    active = [r for r in resources if r.status == "active"]
    by_type: dict[str, list[Resource]] = defaultdict(list)
    for r in active:
        by_type[r.type].append(r)

    lines = [
        "# Free AI Resources",
        "",
        f"_Auto-generated by free-yolo on {date.today().isoformat()} · "
        f"{len(active)} active resources._",
        "",
        "> Free resources to **learn, use and understand AI**. New here? Start with the "
        "route below. Time-sensitive items are flagged so you don't miss them the way we "
        "missed Google's 5-Day Gen AI Intensive.",
        "",
    ]

    # Beginner on-ramp
    stops = []
    for matches, why in _PATH:
        hit = next((r for r in active
                    if any(m in f"{r.title} {r.url}".lower() for m in matches)), None)
        if hit:
            stops.append((hit, why))
    if stops:
        lines += ["## 🚀 New to AI? Start here", ""]
        for i, (r, why) in enumerate(stops, 1):
            lines.append(f"{i}. [{r.title}]({r.url}) — _{_COST_LABEL.get(r.cost, 'Free')}_  \n   {why}")
        lines.append("")

    upcoming = sorted((r for r in active if r.is_time_sensitive),
                      key=lambda r: r.event_date or "")
    if upcoming:
        lines += ["## ⏰ Don't miss — has a date/deadline", ""]
        for r in upcoming:
            lines.append(_line(r, show_date=True))
        lines.append("")

    for t in _TYPE_ORDER:
        items = sorted(by_type.get(t, []), key=_relevance_key)
        if not items:
            continue
        lines += [f"## {_TYPE_LABEL[t]}", ""]
        for r in items:
            lines.append(_line(r))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _line(r: Resource, show_date: bool = False) -> str:
    bits = [f"- [{r.title}]({r.url})"]
    if r.provider:
        bits.append(f"— _{r.provider}_")
    badges = [_COST_LABEL.get(r.cost, "Free")]
    if _level(r):
        badges.append(_level(r))
    bits.append("· " + " · ".join(badges))
    if show_date and r.event_date:
        bits.append(f"**📅 {r.event_date}**")
    if r.topics:
        bits.append(" ".join(f"`{t}`" for t in r.topics))
    if r.description:
        bits.append("\n  " + r.description.replace("\n", " ").strip())
    return " ".join(bits)


def write(resources: list[Resource], path: Path | str) -> Path:
    path = Path(path)
    path.write_text(render(resources))
    return path
