"""Render the catalog to RESOURCES.md — a navigable, beginner-first list that
mirrors the web page: table of contents, Start-here path, recently-added pulse,
deadline urgency, cost/level/curated signals, relevance-sorted type sections.
"""

from __future__ import annotations

from collections import defaultdict
from datetime import date, datetime
from pathlib import Path

from .models import Resource

_TYPE_ORDER = [
    "event", "course", "tutorial", "video", "book",
    "tool", "dataset", "paper", "community", "newsletter", "article", "other",
]
_TYPE_LABEL = {
    "event": "🗓️ Events & live cohorts (time-sensitive)",
    "course": "🎓 Courses",
    "tutorial": "📝 Tutorials & guides",
    "video": "🎬 Videos & lectures",
    "book": "📚 Books",
    "tool": "🛠️ Tools & playgrounds",
    "dataset": "🗂️ Datasets",
    "paper": "📄 Papers",
    "community": "💬 Communities",
    "newsletter": "📰 Newsletters",
    "article": "🧵 Articles",
    "other": "🔗 Other",
}

_COST_LABEL = {"free": "Free", "free-account": "Free · sign-up", "freemium": "Freemium"}
_ADV = {"fine-tuning", "mlops", "evals", "agents", "rag"}

_PATH = [
    (["elements of ai"], "No code, no math — understand what AI is and is not."),
    (["3blue1brown"], "See, visually, how a neural network actually works."),
    (["machine learning crash course"], "Your first hands-on ML, right in the browser."),
    (["llm course"], "Cross from AI user to AI builder with language models."),
    (["practical deep learning", "course.fast"], "Build and ship real models, code-first."),
]


def _slug(label: str) -> str:
    """GitHub-compatible heading anchor: lowercase, drop non-[alnum/space/-/_],
    spaces→hyphens, keeping the leading hyphen a leading emoji leaves behind."""
    kept = "".join(ch for ch in label.lower() if ch.isalnum() or ch in " -_")
    return kept.replace(" ", "-")


def _level(r: Resource) -> str:
    if "fundamentals" in r.topics:
        return "Beginner"
    if any(t in _ADV for t in r.topics):
        return "Intermediate"
    return ""


def _relevance_key(r: Resource):
    return (0 if "fundamentals" in r.topics else 1,
            0 if r.cost == "free" else 1,
            r.title.lower())


def _urgency(r: Resource) -> str:
    if not r.event_date:
        return ""
    try:
        n = (datetime.fromisoformat(r.event_date).date() - date.today()).days
    except ValueError:
        return ""
    if n < 0:
        return ""
    if n == 0:
        return " · 🔴 closes today"
    if n <= 7:
        return f" · 🔴 closes in {n}d"
    if n <= 30:
        return f" · ⏳ in {n}d"
    return ""


def render(resources: list[Resource]) -> str:
    active = [r for r in resources if r.status == "active"]
    by_type: dict[str, list[Resource]] = defaultdict(list)
    for r in active:
        by_type[r.type].append(r)

    # Beginner on-ramp
    stops = []
    for matches, why in _PATH:
        hit = next((r for r in active
                    if any(m in f"{r.title} {r.url}".lower() for m in matches)), None)
        if hit:
            stops.append((hit, why))

    # Recently added (found_at = first seen), excluding the catalog's birth day
    min_found = min((r.found_at for r in active), default="")
    recently = sorted((r for r in active if r.found_at and r.found_at != min_found),
                      key=lambda r: r.found_at, reverse=True)[:10]

    upcoming = sorted((r for r in active if r.is_time_sensitive),
                      key=lambda r: r.event_date or "")
    shown = {r.id for r in upcoming}     # so dated items aren't repeated below

    # type sections (deduped against the deadline list, relevance-sorted)
    type_sections = []
    for t in _TYPE_ORDER:
        items = sorted((r for r in by_type.get(t, []) if r.id not in shown),
                       key=_relevance_key)
        if items:
            type_sections.append((t, items))

    # ---- assemble ----
    lines = [
        "# Free AI Resources",
        "",
        f"_Auto-generated by free-yolo on {date.today().isoformat()} · "
        f"{len(active)} active resources._",
        "",
        "> Free resources to **learn, use and understand AI**. New here? Start with the "
        "route below. Time-sensitive items are flagged so you don't miss them the way we "
        "missed Google's 5-Day Gen AI Intensive.",
        "",
    ]

    # Table of contents
    toc = []
    if stops:
        toc.append(("🚀 New to AI? Start here", len(stops)))
    if recently:
        toc.append(("🆕 Recently added", len(recently)))
    if upcoming:
        toc.append(("⏰ Don't miss — has a date/deadline", len(upcoming)))
    for t, items in type_sections:
        toc.append((_TYPE_LABEL[t], len(items)))
    if toc:
        lines += ["## Contents", ""]
        lines += [f"- [{label}](#{_slug(label)}) ({n})" for label, n in toc]
        lines.append("")

    if stops:
        lines += ["## 🚀 New to AI? Start here", ""]
        for i, (r, why) in enumerate(stops, 1):
            lines.append(f"{i}. [{r.title}]({r.url}) — _{_COST_LABEL.get(r.cost, 'Free')}_  \n   {why}")
        lines.append("")

    if recently:
        lines += ["## 🆕 Recently added", ""]
        for r in recently:
            lines.append(_line(r) + f"  \n  _added {r.found_at}_")
        lines.append("")

    if upcoming:
        lines += ["## ⏰ Don't miss — has a date/deadline", ""]
        for r in upcoming:
            lines.append(_line(r, show_date=True))
        lines.append("")

    for t, items in type_sections:
        lines += [f"## {_TYPE_LABEL[t]}", ""]
        for r in items:
            lines.append(_line(r))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _line(r: Resource, show_date: bool = False) -> str:
    bits = [f"- [{r.title}]({r.url})"]
    if r.provider:
        bits.append(f"— _{r.provider}_")
    badges = [_COST_LABEL.get(r.cost, "Free")]
    if _level(r):
        badges.append(_level(r))
    if r.source == "seed":
        badges.append("✦ curated")
    bits.append("· " + " · ".join(badges))
    if show_date and r.event_date:
        bits.append(f"**📅 {r.event_date}**{_urgency(r)}")
    if r.topics:
        bits.append(" ".join(f"`{t}`" for t in r.topics))
    if r.description:
        bits.append("\n  " + r.description.replace("\n", " ").strip())
    return " ".join(bits)


def write(resources: list[Resource], path: Path | str) -> Path:
    path = Path(path)
    path.write_text(render(resources))
    return path
