"""Render the catalog to a single self-contained static HTML page.

No build step, no server, no framework: data is embedded as JSON and filtered
client-side. Drop site/index.html on GitHub Pages (free) and you're done.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

from .models import Resource

_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Free AI Resources</title>
<style>
  :root {{ --bg:#0d1117; --card:#161b22; --line:#30363d; --fg:#e6edf3;
           --muted:#8b949e; --accent:#58a6ff; --warn:#f0883e; }}
  * {{ box-sizing:border-box; }}
  body {{ margin:0; font:15px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;
         background:var(--bg); color:var(--fg); }}
  header {{ padding:32px 20px 8px; max-width:960px; margin:0 auto; }}
  h1 {{ margin:0 0 4px; font-size:26px; }}
  .sub {{ color:var(--muted); margin-bottom:16px; }}
  .controls {{ max-width:960px; margin:0 auto; padding:0 20px;
               display:flex; gap:8px; flex-wrap:wrap; align-items:center; }}
  input, select {{ background:var(--card); color:var(--fg); border:1px solid var(--line);
                   border-radius:8px; padding:8px 10px; font-size:14px; }}
  #q {{ flex:1; min-width:200px; }}
  main {{ max-width:960px; margin:16px auto; padding:0 20px 60px;
          display:grid; gap:12px; }}
  .card {{ background:var(--card); border:1px solid var(--line); border-radius:10px;
           padding:14px 16px; }}
  .card.dated {{ border-left:3px solid var(--warn); }}
  .card a.t {{ color:var(--accent); font-weight:600; text-decoration:none; font-size:16px; }}
  .card a.t:hover {{ text-decoration:underline; }}
  .meta {{ color:var(--muted); font-size:13px; margin:4px 0; }}
  .desc {{ font-size:14px; margin:6px 0 0; }}
  .tags {{ margin-top:8px; display:flex; gap:6px; flex-wrap:wrap; }}
  .tag {{ background:#21262d; color:var(--muted); border-radius:12px;
          padding:2px 9px; font-size:12px; }}
  .date {{ color:var(--warn); font-weight:600; }}
  .count {{ color:var(--muted); font-size:13px; padding:8px 20px; max-width:960px;
            margin:0 auto; }}
  footer {{ text-align:center; color:var(--muted); font-size:12px; padding:24px; }}
</style>
</head>
<body>
<header>
  <h1>🦾 Free AI Resources</h1>
  <div class="sub">Free ways to learn, use and understand AI · {n} active ·
    updated {today}. Items with a 📅 date are time-sensitive — grab them early.</div>
</header>
<div class="controls">
  <input id="q" placeholder="Search title, provider, description…">
  <select id="type"><option value="">All types</option></select>
  <select id="topic"><option value="">All topics</option></select>
  <select id="sort">
    <option value="date">Sort: deadline first</option>
    <option value="title">Sort: title</option>
    <option value="found">Sort: newest found</option>
  </select>
</div>
<div class="count" id="count"></div>
<main id="list"></main>
<footer>Generated by free-yolo · data is open, contributions welcome.</footer>
<script>
const DATA = {data};
const $ = s => document.querySelector(s);
const list = $('#list'), q = $('#q'), typeSel = $('#type'),
      topicSel = $('#topic'), sortSel = $('#sort'), count = $('#count');

const types = [...new Set(DATA.map(r => r.type))].sort();
const topics = [...new Set(DATA.flatMap(r => r.topics))].sort();
for (const t of types) typeSel.add(new Option(t, t));
for (const t of topics) topicSel.add(new Option(t, t));

function render() {{
  const term = q.value.toLowerCase();
  const ft = typeSel.value, fp = topicSel.value;
  let rows = DATA.filter(r =>
    (!ft || r.type === ft) &&
    (!fp || r.topics.includes(fp)) &&
    (!term || (r.title + ' ' + r.provider + ' ' + r.description).toLowerCase().includes(term)));
  const s = sortSel.value;
  rows.sort((a, b) =>
    s === 'title' ? a.title.localeCompare(b.title) :
    s === 'found' ? (b.found_at || '').localeCompare(a.found_at || '') :
    // deadline first: dated items ascending, then the rest
    (a.event_date ? 0 : 1) - (b.event_date ? 0 : 1)
      || (a.event_date || '').localeCompare(b.event_date || ''));
  count.textContent = rows.length + ' resources';
  list.innerHTML = rows.map(r => `
    <div class="card ${{r.event_date ? 'dated' : ''}}">
      <a class="t" href="${{r.url}}" target="_blank" rel="noopener">${{esc(r.title)}}</a>
      <div class="meta">
        ${{r.provider ? esc(r.provider) + ' · ' : ''}}${{r.type}}
        ${{r.event_date ? ' · <span class="date">📅 ' + r.event_date + '</span>' : ''}}
      </div>
      ${{r.description ? `<div class="desc">${{esc(r.description)}}</div>` : ''}}
      <div class="tags">${{r.topics.map(t => `<span class="tag">${{t}}</span>`).join('')}}</div>
    </div>`).join('');
}}
function esc(s) {{ return (s || '').replace(/[&<>]/g, c => ({{'&':'&amp;','<':'&lt;','>':'&gt;'}}[c])); }}
[q, typeSel, topicSel, sortSel].forEach(el => el.addEventListener('input', render));
render();
</script>
</body>
</html>
"""


def render(resources: list[Resource]) -> str:
    active = [r for r in resources if r.status == "active"]
    payload = [
        {
            "title": r.title, "url": r.url, "description": r.description,
            "type": r.type, "topics": r.topics, "provider": r.provider,
            "event_date": r.event_date, "found_at": r.found_at,
        }
        for r in active
    ]
    return _TEMPLATE.format(
        n=len(active),
        today=date.today().isoformat(),
        data=json.dumps(payload, ensure_ascii=False),
    )


def write(resources: list[Resource], path: Path | str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(resources))
    return path
